### ISSUE TITLE
No gradle-wrapper.jar

### ISSUE THREAD

**Issue by AntonLindell** [Bokun/inventory_sample_plugin#1]
I can't build this sample plugin since there is no gradle-wrapper.jar in the ./gradle/wrapper/ folder. Is there another way to try the plugin that I'm missing?

Thanks.

**Comment by mindas** [comment]
https://github.com/Bokun/inventory_sample_plugin/commit/970c512f6dc9956dedeca96ca8a33a5b67af6ecd should have fixed that. Thanks for letting us know.
